# Generated by Django 2.1.4 on 2018-12-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0004_card_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='list',
            new_name='listId',
        ),
    ]
