# Generated by Django 2.1.4 on 2018-12-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0005_auto_20181213_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='listId',
            new_name='list',
        ),
    ]
