# Generated by Django 2.1.4 on 2018-12-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0008_auto_20181214_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='descripation',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
